development:
  host: 127.0.0.1
  port: 6379
  slot: 0

test:
  host: 127.0.0.1
  port: 6379
  slot: 0

staging:
  host: <%= ENV['REDIS_HOST'] %>
  port: 6379
  slot: 0

production:
  host: <%= ENV['REDIS_HOST'] %>
  port: 6379
  slot: 0
